### PR TITLE
Push SMaSH towards easier programmatic use

### PR DESCRIPTION
**Pull request by spaugh**
SMaSH has good potential, but the combination of various scripts of different languages as well as the inflexible interface make it difficult to include in any other pieces of code. Personally, I want to be able to run SMaSH again and again on many datasets - In its current condition, this would be accomplished through a bunch of hacks. I think it would be good for the adoption of the tool to be easy to use.

Towards this end, I've put the "main script" section into a main function, while making a VariantComparator class, replacing optparse (deprecated) with argparse, worked towards following Python coding standards, restructured the source code in preparation for pip-installability, re-wrote the sortByRef perl script in Python, and attempted to do some minor cleanup. I think this is only one step in the right direction, but my fork definitely includes some good improvements already (more are coming).

### CODE REVIEW

**Comment by jn80842** [comment]
Thanks -- this looks really good! Unfortunately it's a busy time of year for us and I probably won't be able to merge this until next week, but we definitely appreciate the contribution.

**Comment by spaugh** [comment]
Glad you like the changes. I'm also planning on integrating the vcf canonicalization into the main script - I think that will make a big difference in usability.

**Comment by spaugh** [comment]
Any updates on when this will likely be merged?

**Comment by jn80842** [comment]
I'm aiming for this weekend.

**Comment by jn80842** [comment]
Apologies for taking so long to get to this. I merged almost all of your changes -- the VariantComparator class is definitely moving in the right direction, but I ran it on our Venter mpileup vcf and got different results than the old code so I've backed it out for now. I also changed the name of the package as we're planning on supporting the ADAM format as well as vcf.

Thanks for the contribution!

**Comment by spaugh** [comment]
No problem. The different results are strange...I'll look into it asap.

**Pull request merged**
